// Static enrichment data sourced from Fragrantica.
// Key format: "brand|name" (both lowercased and trimmed).
// Only fields blank in the Google Sheet are filled in; sheet values always win.

export const FRAGRANCE_ENRICHMENT = {
  'abel|cyan nori': {
    olfactorygroup: 'Aromatic Fruity',
    topnotes: 'Tangerine, White Peach',
    heartnotes: 'Musk',
    basenotes: 'Seaweed',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime, summer',
    vibe: 'fresh, fruity, summery, light',
    comparableto: 'Jo Malone Peony & Blush Suede, Maison Margiela Replica Flower Market',
  },
  'abel|nurture': {
    olfactorygroup: 'Floral Woody Musk',
    topnotes: 'Mastic, Orange Blossom, Bulgarian Rose',
    heartnotes: 'Ginger, Jasmine Sambac',
    basenotes: 'Sandalwood',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime',
    vibe: 'warm, soft, comforting, floral',
    comparableto: 'Glossier You, Jo Malone Jasmine Sambac & Marigold',
  },
  'aesop|marrakech intense': {
    olfactorygroup: 'Woody Spicy',
    topnotes: 'Cypress, Atlas Cedar, Cardamom',
    heartnotes: 'Cumin, Atlas Cedar, Black Pepper',
    basenotes: 'Cypriol, Sandalwood, Atlas Cedar',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, evening, cooler weather',
    vibe: 'earthy, spicy, mysterious, bold',
    comparableto: 'Le Labo Santal 33, Diptyque Tam Dao',
  },
  'aesop|gloam': {
    olfactorygroup: 'Woody Spicy',
    topnotes: 'Saffron',
    heartnotes: 'Mimosa, Iris, Jasmine Sambac',
    basenotes: 'Woody Notes',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, casual, cooler weather',
    vibe: 'sophisticated, warm, powdery, evening',
    comparableto: 'Chanel No.5, YSL Mon Paris',
  },
  "byredo|bal d'afrique": {
    olfactorygroup: 'Floral Woody',
    topnotes: 'Bergamot, Lemon, Violet Leaf',
    heartnotes: 'African Marigold, Neroli, Jasmine, Violet',
    basenotes: 'Musk, Vetiver, Cedarwood, Amber',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime, summer, outdoor',
    vibe: 'summery, breezy, uplifting, feminine',
    comparableto: 'Jo Malone Wood Sage & Sea Salt, Dior J\'adore',
  },
  'byredo|gypsy water': {
    olfactorygroup: 'Woody Aromatic',
    topnotes: 'Bergamot, Lemon, Pepper',
    heartnotes: 'Incense, Orris, Pine Needles',
    basenotes: 'Amber, Sandalwood, Vanilla',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, evening, cooler weather',
    vibe: 'earthy, forest-y, mysterious, cosy',
    comparableto: 'Diptyque Tam Dao, Tom Ford Oud Wood',
  },
  'byredo|animalique': {
    olfactorygroup: 'Oriental Floral',
    topnotes: 'Bergamot, Lemon',
    heartnotes: 'Violet, Mimosa',
    basenotes: 'Suede, Tobacco Leaf, Amber',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, date night',
    vibe: 'sensual, warm, bold, evening',
    comparableto: 'YSL Black Opium, Tom Ford Noir de Noir',
  },
  'byredo|mojave ghost': {
    olfactorygroup: 'Floral Woody Musk',
    topnotes: 'Ambrette, Magnolia, Snow Lotus',
    heartnotes: 'Violet, Sandalwood, Hawthorn',
    basenotes: 'Cedarwood, Musks, Amberwood',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime',
    vibe: 'clean, airy, soft, minimalist',
    comparableto: 'Glossier You, Maison Margiela Replica Flower Market',
  },
  'byredo|mixed emotions': {
    olfactorygroup: 'Woody Aromatic',
    topnotes: 'Black Currant, Maté',
    heartnotes: 'Tea, Violet Leaf',
    basenotes: 'Birch, Papyrus',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime, office',
    vibe: 'fresh, understated, office-safe, unisex',
    comparableto: 'Le Labo Thé Noir 29, Diptyque L\'Ombre dans l\'Eau',
  },
  'byredo|bibliothèque': {
    olfactorygroup: 'Floral Woody Musk',
    topnotes: 'Plum, Peach',
    heartnotes: 'Violet, Peony',
    basenotes: 'Leather, Patchouli, Vanilla, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, cooler weather, casual',
    vibe: 'cosy, warm, sophisticated, literary',
    comparableto: 'Maison Margiela Replica By the Fireplace, Juliette Has a Gun Not a Perfume',
  },
  'byredo|young rose': {
    olfactorygroup: 'Floral Woody Musk',
    topnotes: 'Sichuan Pepper, Ambrette Seed',
    heartnotes: 'Damask Rose, Iris',
    basenotes: 'Musk, Ambroxan',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime, spring',
    vibe: 'fresh, modern rose, clean, spring',
    comparableto: 'Dior Miss Dior Blooming Bouquet, Chanel Chance Eau Tendre',
  },
  'byredo|blanche': {
    olfactorygroup: 'Floral Musk',
    topnotes: 'Aldehydes, Pink Pepper',
    heartnotes: 'Peony, Violet',
    basenotes: 'Musk, Woody Notes',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime, office',
    vibe: 'clean, powdery, soft, ethereal',
    comparableto: 'Chanel Chance Eau Tendre, Narciso Rodriguez For Her',
  },
  'byredo|accord oud': {
    olfactorygroup: 'Oriental Spicy',
    topnotes: 'Blackberry, Rum, Saffron',
    heartnotes: 'Leather, Agarwood (Oud), Clary Sage',
    basenotes: 'Patchouli, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Strong',
    occasion: 'Evening, formal, special occasion',
    vibe: 'bold, smoky, dark, evening',
    comparableto: 'Tom Ford Oud Wood, YSL Black Opium',
  },
  'chris collins|oud galore': {
    olfactorygroup: 'Woody Floral',
    topnotes: 'Mint, Cinnamon, Madagascar Cloves',
    heartnotes: 'Rose, Geranium, Orris, Agarwood (Oud)',
    basenotes: 'Sandalwood, Cypriol, Copahu Balm, Incense',
    longevity: 'Very long (10+ hours)',
    sillage: 'Strong',
    occasion: 'Evening, special occasion',
    vibe: 'opulent, floral, spicy, special occasion',
    comparableto: 'Tom Ford Rose Prick, Maison Francis Kurkdjian Oud',
  },
  'acqua di parma|fico di amalfi': {
    olfactorygroup: 'Citrus Aromatic',
    topnotes: 'Grapefruit, Bergamot, Citron, Lemon',
    heartnotes: 'Fig Nectar, Jasmine, Pink Pepper',
    basenotes: 'Fig Tree, Cedar, Benzoin',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime, outdoor events',
    vibe: 'fresh, bright, Mediterranean, summery',
    comparableto: 'Jo Malone Lime Basil & Mandarin, Hermès Un Jardin en Méditerranée',
  },
  'acqua di parma|colonia': {
    olfactorygroup: 'Citrus Aromatic',
    topnotes: 'Lemon, Sweet Orange, Calabrian Bergamot',
    heartnotes: 'Lavender, Rose, Verbena, Rosemary',
    basenotes: 'Vetiver, Sandalwood, Patchouli',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Formal, casual, daytime, summer',
    vibe: 'clean, classic, timeless, crisp',
    comparableto: 'Hermès Eau d\'Orange Verte, Jo Malone Nectarine Blossom & Honey',
  },
  'comme des garçon|marseille': {
    olfactorygroup: 'Aquatic / Marine',
    topnotes: 'Marine Notes, Sea Salt, Seaweed',
    heartnotes: 'Jasmine, Rose, Carnation',
    basenotes: 'Musk, Driftwood, Ambergris',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime, summer',
    vibe: 'oceanic, beachy, clean, airy',
    comparableto: 'Jo Malone Wood Sage & Sea Salt, Davidoff Cool Water',
  },
  'creed|royal oud': {
    olfactorygroup: 'Woody / Oud',
    topnotes: 'Bergamot, Grapefruit, Pink Pepper',
    heartnotes: 'Oud, Geranium, Cinnamon',
    basenotes: 'Cedar, Sandalwood, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Formal, evening, special occasion',
    vibe: 'sophisticated, rich, formal, timeless',
    comparableto: 'Tom Ford Oud Wood, Dior Sauvage Elixir',
  },
  'diptyque|do son': {
    olfactorygroup: 'Floral',
    topnotes: 'Tuberose, White Pepper',
    heartnotes: 'Tuberose, Rose',
    basenotes: 'Musk, Sandalwood, Cedarwood',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime, spring, summer',
    vibe: 'romantic, creamy, feminine, warm floral',
    comparableto: 'Marc Jacobs Daisy, Dior Miss Dior',
  },
  'diptyque|oud palao': {
    olfactorygroup: 'Oud / Woody',
    topnotes: 'Bergamot, Patchouli Leaves',
    heartnotes: 'Oud, Patchouli',
    basenotes: 'Sandalwood, Vetiver, Amber',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, cooler weather',
    vibe: 'earthy, rich, grounding, warm',
    comparableto: 'Le Labo Oud 27, Tom Ford Oud Wood',
  },
  'ella k|rose de pushkar': {
    olfactorygroup: 'Floral / Rose',
    topnotes: 'Bergamot, Pink Pepper',
    heartnotes: 'Turkish Rose, Geranium',
    basenotes: 'Sandalwood, Patchouli, Musk',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime',
    vibe: 'romantic, rosy, feminine, classic',
    comparableto: 'Lancôme La Vie est Belle, Dior Miss Dior',
  },
  'frederic malle|vetiver extraordinaire (dominique ropion)': {
    olfactorygroup: 'Woody / Chypre',
    topnotes: 'Grapefruit, Bergamot',
    heartnotes: 'Vetiver, Rose, Jasmine',
    basenotes: 'Vetiver, Sandalwood, Amber',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Formal, casual, year-round',
    vibe: 'sophisticated, earthy, unisex, versatile',
    comparableto: 'Hermès Terre d\'Hermès, Chanel Sycomore',
  },
  'frederic maller|vetiver extraordinaire (dominique ropion)': {
    olfactorygroup: 'Woody / Chypre',
    topnotes: 'Grapefruit, Bergamot',
    heartnotes: 'Vetiver, Rose, Jasmine',
    basenotes: 'Vetiver, Sandalwood, Amber',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Formal, casual, year-round',
    vibe: 'sophisticated, earthy, unisex, versatile',
    comparableto: 'Hermès Terre d\'Hermès, Chanel Sycomore',
  },
  'fugazzi|vanilla haze': {
    olfactorygroup: 'Oriental Vanilla',
    topnotes: 'Almond, Hazelnut, Coconut Milk, Mandarin',
    heartnotes: 'Vanilla Pod, Tonka Bean, Jasmine',
    basenotes: 'Caramel, Musk, Cashmere Wood, Amber',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, casual, cooler weather',
    vibe: 'sweet, cosy, indulgent, dessert-like',
    comparableto: 'Tom Ford Tobacco Vanille, Maison Margiela Replica By the Fireplace',
  },
  'goldfield & banks|pacific rock moss': {
    olfactorygroup: 'Aromatic Aquatic',
    topnotes: 'Italian Lemon, Sage',
    heartnotes: 'Geranium, Moss',
    basenotes: 'Virginia Cedar',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime, outdoor, summer',
    vibe: 'fresh, green, outdoorsy, clean',
    comparableto: 'Jo Malone Wood Sage & Sea Salt, Hermès Un Jardin sur le Nil',
  },
  'initio|atomic rose': {
    olfactorygroup: 'Oriental Floral',
    topnotes: 'Pink Pepper, Bergamot',
    heartnotes: 'Bulgarian Rose',
    basenotes: 'Vanilla, Amber, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Strong',
    occasion: 'Casual, evening, year-round',
    vibe: 'bold, romantic, warm, evening',
    comparableto: 'Giorgio Armani Sì, Lancôme La Nuit Trésor',
  },
  'initio|oud for greatness': {
    olfactorygroup: 'Oud / Oriental',
    topnotes: 'Bergamot, Cardamom',
    heartnotes: 'Oud, Rose Essence',
    basenotes: 'Musks, Ambergris, Cypriol',
    longevity: 'Very long (10+ hours)',
    sillage: 'Strong',
    occasion: 'Evening, formal, special occasion',
    vibe: 'bold, opulent, powerful, dark',
    comparableto: 'Tom Ford Oud Wood, Creed Royal Oud',
  },
  'jade888|hermetica': {
    olfactorygroup: 'Floral / Woody',
    topnotes: 'Bergamot, Pink Pepper, Violet Leaf',
    heartnotes: 'Jasmine, Gardenia, Green Tea',
    basenotes: 'Sandalwood, Musk, Amber',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime',
    vibe: 'fresh, floral, clean, feminine',
    comparableto: 'Dior J\'adore, Jo Malone Peony & Blush Suede',
  },
  'jo malone|velvet rose & oud': {
    olfactorygroup: 'Floral / Oud',
    topnotes: 'Raspberry, Rose',
    heartnotes: 'Rose, Oud',
    basenotes: 'Sandalwood, Benzoin, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, formal, cooler weather',
    vibe: 'romantic, rich, warm, special',
    comparableto: 'Tom Ford Rose Prick, Dior Miss Dior',
  },
  'jo malone|myrhh and tonka': {
    olfactorygroup: 'Oriental / Gourmand',
    topnotes: 'Lavender, Heliotrope, Almond',
    heartnotes: 'Myrrh',
    basenotes: 'Tonka Bean, Sandalwood, Benzoin',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, cooler weather, casual',
    vibe: 'cosy, sweet, comforting, warm',
    comparableto: 'Tom Ford Tobacco Vanille, YSL Black Opium',
  },
  'juliette has a gun|vanilla vibes': {
    olfactorygroup: 'Gourmand / Floral',
    topnotes: 'Pink Pepper, Grapefruit, Bergamot',
    heartnotes: 'Heliotrope, Vanilla, Jasmine',
    basenotes: 'Cashmeran, Musk, Vanilla',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, evening',
    vibe: 'playful, sweet, flirty, casual',
    comparableto: 'Lancôme La Vie est Belle, Dior Miss Dior Blooming Bouquet',
  },
  'juliette has a gun|ego stratis': {
    olfactorygroup: 'Citrus Aquatic',
    topnotes: 'Bergamot, Lemon, Mandarin',
    heartnotes: 'Sea Notes, Calone, Blueberry, Neroli, Peach',
    basenotes: 'Ambroxan, Musk, Cedar',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime, summer',
    vibe: 'fresh, clean, airy, summery',
    comparableto: 'Issey Miyake L\'Eau d\'Issey, Davidoff Cool Water',
  },
  'juliette has a gun|magnolia bliss': {
    olfactorygroup: 'Floral Fruity',
    topnotes: 'Lemon, Bergamot, Petitgrain, Ginger',
    heartnotes: 'Nectarine, Magnolia, Freesia, Peony, Greengage',
    basenotes: 'Musk, Ambroxan, Vanilla, Tonka Bean',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, spring, daytime',
    vibe: 'fresh, fruity, feminine, spring',
    comparableto: 'Marc Jacobs Daisy, Jo Malone Peony & Blush Suede',
  },
  'le labo|thé matcha 26': {
    olfactorygroup: 'Green / Woody',
    topnotes: 'Bergamot, Lemon',
    heartnotes: 'Matcha Tea, Galbanum',
    basenotes: 'Vetiver, Sandalwood, Musk',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime',
    vibe: 'serene, green, earthy, zen',
    comparableto: 'Diptyque Philosykos, Hermès Un Jardin sur le Nil',
  },
  'le labo|santal 33': {
    olfactorygroup: 'Woody / Musky',
    topnotes: 'Violet, Cardamom',
    heartnotes: 'Iris, Ambrette',
    basenotes: 'Sandalwood, Cedarwood, Papyrus',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, everyday, year-round',
    vibe: 'warm, smoky, unisex, cult classic',
    comparableto: 'Byredo Gypsy Water, Tom Ford Oud Wood (lighter)',
  },
  'le labo |oud 27': {
    olfactorygroup: 'Oud / Woody',
    topnotes: 'Oud, Sandalwood',
    heartnotes: 'Oud, Cumin, Labdanum',
    basenotes: 'Sandalwood, Amber, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Strong',
    occasion: 'Evening, special occasion',
    vibe: 'dark, intense, earthy, bold',
    comparableto: 'Tom Ford Oud Wood, Initio Oud for Greatness',
  },
  'le labo|oud 27': {
    olfactorygroup: 'Oud / Woody',
    topnotes: 'Oud, Sandalwood',
    heartnotes: 'Oud, Cumin, Labdanum',
    basenotes: 'Sandalwood, Amber, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Strong',
    occasion: 'Evening, special occasion',
    vibe: 'dark, intense, earthy, bold',
    comparableto: 'Tom Ford Oud Wood, Initio Oud for Greatness',
  },
  'maison crivelli|oud stallion': {
    olfactorygroup: 'Oriental Woody',
    topnotes: 'Saffron, Cardamom, Indonesian Nutmeg',
    heartnotes: 'Jasmine, Osmanthus, Turkish Rose',
    basenotes: 'Agarwood (Oud), Leather, Cedar, Patchouli, Tonka',
    longevity: 'Very long (10+ hours)',
    sillage: 'Strong',
    occasion: 'Evening, formal, cooler weather',
    vibe: 'opulent, rich, complex, evening',
    comparableto: 'Tom Ford Oud Wood, Creed Royal Oud',
  },
  'maison crivelli|payrus moléculaire': {
    olfactorygroup: 'Floral Woody Musk',
    topnotes: 'Black Pepper, Coriander, Elemi',
    heartnotes: 'Papyrus, Amyris, Carrot Seeds',
    basenotes: 'Tonka Bean, Tobacco, Olibanum',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, daytime, office',
    vibe: 'sophisticated, earthy, understated, office-safe',
    comparableto: 'Byredo Mixed Emotions, Le Labo Santal 33',
  },
  'maison francis kurkdjian|aqua media cologne forte': {
    olfactorygroup: 'Citrus Aromatic',
    topnotes: 'Bergamot, Lemon, Lime',
    heartnotes: 'Petitgrain, Neroli, Basil',
    basenotes: 'Musk, Vetiver, Cedarwood',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime, summer, office',
    vibe: 'fresh, clean, energising, office-safe',
    comparableto: 'Acqua di Parma Colonia, Jo Malone Lime Basil & Mandarin',
  },
  'maison francis kurkdjian|baccarat rouge': {
    olfactorygroup: 'Floral Woody Amber',
    topnotes: 'Jasmine, Saffron',
    heartnotes: 'Amberwood, Ambergris',
    basenotes: 'Fir Resin, Cedar',
    longevity: 'Very long (10+ hours)',
    sillage: 'Strong',
    occasion: 'Evening, formal, year-round',
    vibe: 'iconic, warm, golden, distinctive',
    comparableto: 'Nothing quite like it — the most-talked-about scent of the decade',
  },
  "maison francis kurkdjian|l'homme a la rose": {
    olfactorygroup: 'Floral / Citrus',
    topnotes: 'Grapefruit, Bergamot, Mandarin',
    heartnotes: 'Rose, Grasse Rose',
    basenotes: 'Musk, Cedarwood, Vetiver',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, formal, daytime',
    vibe: 'fresh, modern, unisex, elegant',
    comparableto: 'Chanel Chance Eau Vive, Byredo Bal d\'Afrique',
  },
  'maison francis kurkdjian|724': {
    olfactorygroup: 'Floral Musk',
    topnotes: 'Aldehydes, Calabrian Bergamot',
    heartnotes: 'Egyptian Jasmine, Mock Orange, Sweet Pea',
    basenotes: 'White Musk, Sandalwood',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Subtle',
    occasion: 'Casual, office, daytime',
    vibe: 'clean, soft, airy, sophisticated',
    comparableto: 'Maison Margiela Replica Flower Market, Byredo Blanche',
  },
  'maison francis kurkdjian|gentle fluidity silver': {
    olfactorygroup: 'Woody / Amber',
    topnotes: 'Juniper Berries, Nutmeg, Coriander',
    heartnotes: 'Musks, Geranium',
    basenotes: 'Sandalwood, Amber, Vanilla',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, evening, cooler weather',
    vibe: 'warm, woody, versatile, sophisticated',
    comparableto: 'Le Labo Santal 33, Byredo Gypsy Water',
  },
  'maison francis kurkdjian|oud': {
    olfactorygroup: 'Oud / Woody',
    topnotes: 'Oud, Rose',
    heartnotes: 'Oud, Jasmine',
    basenotes: 'Sandalwood, Amber, Musk',
    longevity: 'Very long (10+ hours)',
    sillage: 'Strong',
    occasion: 'Evening, formal, special occasion',
    vibe: 'opulent, bold, statement, evening',
    comparableto: 'Tom Ford Oud Wood, Creed Royal Oud',
  },
  'maison francis kurkdjian|oud edp': {
    olfactorygroup: 'Oud / Woody',
    topnotes: 'Oud, Rose',
    heartnotes: 'Oud, Jasmine',
    basenotes: 'Sandalwood, Amber, Musk',
    longevity: 'Very long (10+ hours)',
    sillage: 'Strong',
    occasion: 'Evening, formal, special occasion',
    vibe: 'opulent, bold, statement, evening',
    comparableto: 'Tom Ford Oud Wood, Creed Royal Oud',
  },
  'marc-antoine barrois|b683 extrait': {
    olfactorygroup: 'Oriental Woody',
    topnotes: 'Safraleine, Green Apple, Pink Pepper',
    heartnotes: 'Agarwood (Oud), Violet Leaf, Cumin',
    basenotes: 'Indonesian Patchouli, Australian Sandalwood, Vanilla',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, formal',
    vibe: 'complex, dark, sophisticated, evening',
    comparableto: 'Tom Ford Noir de Noir, Byredo Accord Oud',
  },
  'marie-jeanne|vetiver santal edp': {
    olfactorygroup: 'Woody / Aromatic',
    topnotes: 'Bergamot, Lemon',
    heartnotes: 'Vetiver, Sandalwood',
    basenotes: 'Sandalwood, Musk, Cedar',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, year-round',
    vibe: 'clean, earthy, grounding, versatile',
    comparableto: 'Hermès Terre d\'Hermès, Frederic Malle Vetiver Extraordinaire',
  },
  'molton brown|recharge black pepper': {
    olfactorygroup: 'Spicy / Woody',
    topnotes: 'Black Pepper, Bergamot, Cardamom',
    heartnotes: 'Ginger, Spices, Clove',
    basenotes: 'Cedarwood, Musk, Vetiver',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime, formal',
    vibe: 'energising, spicy, fresh, everyday',
    comparableto: 'Dior Sauvage, Chanel Allure Homme Sport',
  },
  'parfums de marly|valaya': {
    olfactorygroup: 'Floral Fruity',
    topnotes: 'Aldehydes, White Peach, Bergamot, Mandarin',
    heartnotes: 'Orange Blossom, Lily-of-the-Valley, Vetiver, Mahonia',
    basenotes: 'Musk, Ambroxan, Akigalawood, Vanilla',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, daytime, spring, summer',
    vibe: 'soft, feminine, elegant, daytime',
    comparableto: 'Dior Miss Dior, Lancôme La Vie est Belle',
  },
  'parfums de marly|haltane': {
    olfactorygroup: 'Oriental Spicy',
    topnotes: 'Saffron, Amber, Incense',
    heartnotes: 'Rose, Cinnamon, Cardamom',
    basenotes: 'Vanilla, Musk, Sandalwood',
    longevity: 'Long (7–9 hours)',
    sillage: 'Strong',
    occasion: 'Evening, cooler weather, special occasion',
    vibe: 'bold, spicy, warm, evening',
    comparableto: 'Tom Ford Black Orchid, YSL Opium',
  },
  'parfums de marly|althaïr': {
    olfactorygroup: 'Oriental Gourmand',
    topnotes: 'Orange Blossom, Bergamot, Cinnamon, Cardamom',
    heartnotes: 'Bourbon Vanilla, Elemi',
    basenotes: 'Ambroxan, Guaiac Wood, Musk',
    longevity: 'Long (7–9 hours)',
    sillage: 'Moderate',
    occasion: 'Evening, cooler weather',
    vibe: 'warm, sweet, cosy, evening',
    comparableto: 'Tom Ford Tobacco Vanille, Fugazzi Vanilla Haze',
  },
  'simone andreoli|born from fire': {
    olfactorygroup: 'Oriental Floral',
    topnotes: 'Saffron, Black Pepper',
    heartnotes: 'Rose, Agarwood (Oud), Amyris',
    basenotes: 'Vanilla Absolute, Sugar, Cashmere Wood, Amber, Vetiver',
    longevity: 'Long (7–9 hours)',
    sillage: 'Strong',
    occasion: 'Evening, special occasion',
    vibe: 'dramatic, bold, romantic, evening',
    comparableto: 'Tom Ford Black Orchid, Initio Atomic Rose',
  },
  'ssaint|cosmic bang': {
    olfactorygroup: 'Woody Aromatic',
    topnotes: 'Bergamot, Bay Leaf, Fig',
    heartnotes: 'Vetiver, Cedar, Musk',
    basenotes: 'Tobacco, Hay',
    longevity: 'Moderate (4–6 hours)',
    sillage: 'Moderate',
    occasion: 'Casual, evening',
    vibe: 'earthy, smoky, unisex, mysterious',
    comparableto: 'Le Labo Santal 33, Byredo Mixed Emotions',
  },
}

// Apply enrichment to a list of fragrance items.
// Sheet values always win — only blanks are filled in.
export function applyEnrichment(items) {
  return items.map(item => {
    const key = `${(item['Brand'] || item['brand'] || '').toLowerCase().trim()}|${(item['Name'] || item['name'] || '').toLowerCase().trim()}`
    const patch = FRAGRANCE_ENRICHMENT[key]
    if (!patch) return item

    const enriched = { ...item }
    const FIELD_MAP = {
      olfactorygroup: ['olfactorygroup', 'Olfactory Group'],
      topnotes: ['topnotes', 'Top Notes'],
      heartnotes: ['heartnotes', 'Heart Notes'],
      basenotes: ['basenotes', 'Base Notes'],
      longevity: ['longevity', 'Longevity'],
      sillage: ['sillage', 'Sillage'],
      occasion: ['occasion', 'Occasion'],
      vibe: ['vibe', 'Vibe'],
      comparableto: ['comparableto', 'Comparable To'],
    }
    for (const [patchKey, colNames] of Object.entries(FIELD_MAP)) {
      if (patch[patchKey] && !enriched[colNames[0]]) {
        enriched[colNames[0]] = patch[patchKey]
        enriched[colNames[1]] = patch[patchKey]
      }
    }
    return enriched
  })
}
